# Generated by Django 3.1.4 on 2020-12-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('features', models.TextField(verbose_name='Особенности')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('SIM_count', models.IntegerField(verbose_name='Количество симок')),
                ('OS_type', models.TextField(verbose_name='ОС')),
                ('resolution', models.TextField(verbose_name='Разрешение')),
                ('manufacturer', models.TextField(choices=[('CN', 'Китай'), ('VN', 'Вьетнам'), ('RU', 'Россия')])),
                ('double_camera', models.TextField(verbose_name='Двойная камера')),
                ('headphones_port', models.TextField(verbose_name='Разъем для наушников')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.brand')),
            ],
        ),
    ]
