# Generated by Django 3.1.4 on 2020-12-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='features',
            field=models.TextField(null=True, verbose_name='Особенности'),
        ),
    ]
