# Generated by Django 3.1.4 on 2020-12-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20201223_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='double_camera',
            field=models.TextField(null=True, verbose_name='Двойная камера'),
        ),
    ]
