# Generated by Django 3.1.4 on 2020-12-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20201222_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='title',
            new_name='name',
        ),
    ]
